### ISSUE TITLE
@NacosConfigurationProperties cannot bind A multi-level YAML to javabean

### ISSUE THREAD

**Issue by gxw19874** [nacos-group/nacos-spring-project#179]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

My javabean like that:
```
@NacosConfigurationProperties(prefix = "ebtce.services", dataId = "ebtce.services.yaml", ignoreNestedProperties = true, type = ConfigType.YAML, autoRefreshed = true)
@Configuration
@Data
public class ServicesYaml {
    private String crm ;
    private String app ;
    private Mileage mileage;
}

@Configuration
@Data
public class Mileage {
	private String url;
	private String min;
	private String system;
	private String office;
	private String agent;
}
```

My yaml like that:
```
ebtce:
    services:
        crm: 161121
        app: 21212
        mileage:
            url: http://ebtce-service-open/crm_interface
            min: 100
            system: 1111
            office: 111
            agent: 90666
```
The variable crm can bind “161121” and app can bind “21212”，but mileage is null.

### Describe what you expected to happen

I expected the variable mileage can bind the yaml .

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

My environment is https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-boot-example/nacos-spring-boot-config-example
