### ISSUE TITLE
NacosConfigurationProperties如何做到自动注入

### ISSUE THREAD

**Issue by gougoudetao** [nacos-group/nacos-spring-project#208]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
一个简单的应用配置
``` java
@Data
@NacosConfigurationProperties(prefix = "app", dataId = "123456", autoRefreshed = true, ignoreNestedProperties = true, type = ConfigType.YAML)
@Configuration
public class AppProperties {

    private String env;
    @NacosProperty(value = "app-id")
    private String appId;
    private String userId;
    private String secretKey;
    @NacosProperty(value = "static-domain")
    private String staticDomain;
}
```
但是在使用的时候value却是null

### Describe what you expected to happen

希望在使用的时候可以自动注入配置

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
应用配置
``` yaml
nacos:
  config:
    server-addr: localhost:8848
    data-id: 123456
    group: PREVIEW
    type: yaml
    auto-refresh: true
    bootstrap:
      enable: true
      log-enable: true
```
nacos-config-spring-boot-starter 0.2.4
spring-boot-starter 2.2.2.RELEASE
